### ISSUE TITLE
RPi.GPIO无法使用

### ISSUE THREAD

**Issue by redstonee** [chainsx/cxcore#1]
大佬好！我使用这个系统import RPi.GPIO的时候报错提示这个模块只能在Raspberry Pi上使用。这应该怎么解决呀？

**Comment by chainsx** [comment]
`RPi.GPIO`的确会检测是否为`树莓派`，准确的来说应该是检测是否是raspbian，
具体的解决办法就是使用[UMRnInside的RPi.GPIO模块](https://github.com/UMRnInside/RPi.GPIO)。

**Comment by redstonee** [comment]
谢谢大佬！（话说你的上一个系统（cxcore-ubuntu）可以正常用RPi.GPIO来着）




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "chainsx(cx-dandelion)"<notifications@github.com&gt;; 
发送时间: 2020年4月26日(星期天) 下午4:39
收件人: "chainsx/cxcore"<cxcore@noreply.github.com&gt;; 
抄送: "LinusTorvalds [ ¨ &amp;#xA6; ) ! &amp;#xAA;"<1516235445@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [chainsx/cxcore] RPi.GPIO无法使用 (#1)





 
RPi.GPIO的确会检测是否为树莓派，准确的来说应该是检测是否是raspbian，
 具体的解决办法就是使用UMRnInside的RPi.GPIO模块。

**Comment by chainsx** [comment]
因为ubuntu官方已经出镜像了，所以就不再对ubuntu进行更新。
我的初衷也如此吧。

**Comment by redstonee** [comment]
嗷嗷嗷（話說它用起來確實很好用）


 
---原始邮件---
发件人: "chainsx(cx-dandelion)"<notifications@github.com&gt;
发送时间: 2020年4月28日 15:22:11
收件人: "chainsx/cxcore"<cxcore@noreply.github.com&gt;;
抄送: "DC_RedStone"<1516235445@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [chainsx/cxcore] RPi.GPIO无法使用 (#1)




 
因为ubuntu官方已经出镜像了，所以就不再对ubuntu进行更新。
 我的初衷也如此吧。
